version: '3.5'
services:
  nginx:
    image: nginx
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
      - './public:/var/www/public'
      - './dist:/var/www/dist'
    ports:
      - '80:80'
    networks:
      - proxynet
networks:
  proxynet:
    external:
      name: 'docker_network'
